#Study engine executable

Executable:
	echo "Criando Engine..."

	g++ -W "-DSTUDY_WINDOWS" "-DSTUDY_DLL_BUILD" "-DSTUDY_ENABLE_ASSERTS" -std=c++20 "-Iinclude" "-I..\\StudyEngine\\include" "*.cpp" "-Llib" -lstudy -g -o studyEngine.exe 

	echo "Build completa!!"
