#Study engine executable

Executable:
	echo "Criando Engine..."

	g++ -W "-DSTUDY_WINDOWS" "-DSTUDY_DLL_BUILD" "-DSTUDY_ENABLE_ASSERTS" -std=c++20 "-I\\include" "-I..\\StudyEngine\\src" "-I..\\StudyEngine\\include" *.cpp -g -o studyEngine.exe "-Llib" -lstudy

	echo "Build completa!!"
