#Study engine executable

Executable:
	echo "Criando Engine..."

	g++ "-DSTUDY_WINDOWS" "-DSTUDY_DLL_BUILD" -std=c++20 "-I\\include" "-I..\\StudyEngine\\src" "-I..\\StudyEngine\\include" *.cpp -o studyEngine.exe "-Llib" -lstudy

	echo "Build completa!!"
