#ifndef MOUSEBUTTONCODE_H
#define MOUSEBUTTONCODE_H

#define STUDY_MOUSE_BUTTON_1         0
#define STUDY_MOUSE_BUTTON_2         1
#define STUDY_MOUSE_BUTTON_3         2
#define STUDY_MOUSE_BUTTON_4         3
#define STUDY_MOUSE_BUTTON_5         4
#define STUDY_MOUSE_BUTTON_6         5
#define STUDY_MOUSE_BUTTON_7         6
#define STUDY_MOUSE_BUTTON_8         7
#define STUDY_MOUSE_BUTTON_LAST      STUDY_MOUSE_BUTTON_8
#define STUDY_MOUSE_BUTTON_LEFT      STUDY_MOUSE_BUTTON_1
#define STUDY_MOUSE_BUTTON_RIGHT     STUDY_MOUSE_BUTTON_2
#define STUDY_MOUSE_BUTTON_MIDDLE    STUDY_MOUSE_BUTTON_3


#endif