#Study DLL makefile

dllmake:
	echo "Criando dll..."

	g++ -c -g -DSTUDY_WINDOWS -DSTUDY_DLL_BUILD -DSTUDY_ENABLE_ASSERTS -std=c++20  "-Iinclude"  "src\\*.cpp" "src\\Engine\\*.cpp" "src\\Engine\\imGui\\*.cpp" "src\\Platform\\Windows\\*.cpp" "include\\imGUI\\*.cpp" "include\\GLAD\\*.c"
	g++ -shared -o study.dll *.o -Wl,--out-implib,study.a "-Llib" -lglew32 -lglfw3 -lgdi32 -lopengl32
	del "*.o"

	echo "Destruindo dlls..."

	del "..\Application\*.dll"
	del "..\Application\lib\study.dll" "..\Application\lib\study.a"

	copy "study.dll" "..\Application\"
	copy "lib\glfw3.dll" "..\Application\"
	move "study.dll" "..\Application\lib\"
	move "study.a" "..\Application\lib\"